<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="5" passed="3" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-03-10T14:50:05 CET" name="Suite" finished-at="2024-03-10T14:50:25 CET" duration-ms="19861">
    <groups>
      <group name="Login">
        <method signature="LoginTest.invalidCredentials()[pri:0, instance:iWieczor.Tests.LoginTest@121314f7]" name="invalidCredentials" class="iWieczor.Tests.LoginTest"/>
        <method signature="LoginTest.invalidLogin()[pri:0, instance:iWieczor.Tests.LoginTest@121314f7]" name="invalidLogin" class="iWieczor.Tests.LoginTest"/>
        <method signature="LoginTest.validLogin()[pri:0, instance:iWieczor.Tests.LoginTest@121314f7]" name="validLogin" class="iWieczor.Tests.LoginTest"/>
      </group> <!-- Login -->
    </groups>
    <test started-at="2024-03-10T14:50:05 CET" name="LoginTest" finished-at="2024-03-10T14:50:25 CET" duration-ms="19861">
      <class name="iWieczor.Tests.LoginTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:iWieczor.Tests.LoginTest@121314f7]" started-at="2024-03-10T14:50:05 CET" name="launchApplication" finished-at="2024-03-10T14:50:09 CET" duration-ms="3883" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="invalidCredentials()[pri:0, instance:iWieczor.Tests.LoginTest@121314f7]" started-at="2024-03-10T14:50:09 CET" name="invalidCredentials" finished-at="2024-03-10T14:50:09 CET" duration-ms="209" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:iWieczor.Tests.LoginTest@121314f7]" started-at="2024-03-10T14:50:09 CET" name="tearDown" finished-at="2024-03-10T14:50:09 CET" duration-ms="63" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:iWieczor.Tests.LoginTest@121314f7]" started-at="2024-03-10T14:50:09 CET" name="launchApplication" finished-at="2024-03-10T14:50:12 CET" duration-ms="3075" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="invalidLogin()[pri:0, instance:iWieczor.Tests.LoginTest@121314f7]" started-at="2024-03-10T14:50:12 CET" name="invalidLogin" finished-at="2024-03-10T14:50:13 CET" duration-ms="504" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:iWieczor.Tests.LoginTest@121314f7]" started-at="2024-03-10T14:50:13 CET" name="tearDown" finished-at="2024-03-10T14:50:13 CET" duration-ms="58" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:iWieczor.Tests.LoginTest@121314f7]" started-at="2024-03-10T14:50:13 CET" name="launchApplication" finished-at="2024-03-10T14:50:16 CET" duration-ms="2924" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="validLogin()[pri:0, instance:iWieczor.Tests.LoginTest@121314f7]" started-at="2024-03-10T14:50:16 CET" name="validLogin" finished-at="2024-03-10T14:50:18 CET" duration-ms="2162" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Logout Successfully] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Logout Successfully] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at iWieczor.Tests.LoginTest.validLogin(LoginTest.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:iWieczor.Tests.LoginTest@121314f7]" started-at="2024-03-10T14:50:18 CET" name="tearDown" finished-at="2024-03-10T14:50:18 CET" duration-ms="86" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:iWieczor.Tests.LoginTest@121314f7]" started-at="2024-03-10T14:50:18 CET" name="launchApplication" finished-at="2024-03-10T14:50:21 CET" duration-ms="3024" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="validLogin()[pri:0, instance:iWieczor.Tests.LoginTest@121314f7]" started-at="2024-03-10T14:50:21 CET" name="validLogin" finished-at="2024-03-10T14:50:25 CET" duration-ms="3763" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:iWieczor.Tests.LoginTest@121314f7]" started-at="2024-03-10T14:50:25 CET" name="tearDown" finished-at="2024-03-10T14:50:25 CET" duration-ms="79" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- iWieczor.Tests.LoginTest -->
    </test> <!-- LoginTest -->
  </suite> <!-- Suite -->
</testng-results>
